// <auto-generated />
namespace CarIn.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_Servirty_InMapQuestDirections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Servirty_InMapQuestDirections));
        
        string IMigrationMetadata.Id
        {
            get { return "201306101249399_Add_Servirty_InMapQuestDirections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
