// <auto-generated />
namespace CarIn.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ChangedCoordsInVasttrafikToListOfObj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangedCoordsInVasttrafikToListOfObj));
        
        string IMigrationMetadata.Id
        {
            get { return "201305171331253_ChangedCoordsInVasttrafikToListOfObj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
